# Generated by Django 3.2 on 2023-07-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_comment_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-id'], 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
