# Generated by Django 3.2 on 2023-07-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20230709_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenreTitle',
        ),
    ]
